name: Build libXray v26.9.9 Android

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 50b95979f5db551bd273165cf469e5daaf791341

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27.1"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Android
        uses: android-actions/setup-android@v4

      - name: Install Android packages
        run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: true

      - name: Build
        env:
          GOFLAGS: "-ldflags=-checklinkname=0"
          LIBXRAY_GOMOBILE_VERSION: "v0.0.0-20260908204917-8b95e45f8d3e"
        run: python3 build/main.py android

      - name: Check AAR
        run: test -f libXray.aar

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: libXray-v26.9.9-android
          path: libXray.aar
